### ISSUE TITLE
enable definition cache

### ISSUE THREAD

**Issue by juliangut** [juliangut/slim-php-di#2]
enable reintroduced [enableDefinitionCache](https://github.com/PHP-DI/PHP-DI/pull/564) in PHP-DI6-beta2

**Comment by mnapoli** [comment]
I don't understand this issue?

**Comment by juliangut** [comment]
It is a reminder for me to to add enableDefinitionCache, It appeared in your repo because I referenced the PR so I can quickly find it, sorry to pollute the PR

**Comment by mnapoli** [comment]
Oh man I didn't notice the repository I thought I was on PHP-DI/PHP-DI 😆 

Sorry!
